// <auto-generated />
using System;
using ArcadeX.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcadeX.Api.Migrations
{
    [DbContext(typeof(ArcadeXDbContext))]
    partial class ArcadeXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "RPG",
                            CoverImageUrl = "/images/games/cyberpunk.jpg",
                            Description = "Open-world action RPG set in a dystopian future",
                            DeveloperId = 4,
                            DownloadCount = 12500,
                            Price = 59.99m,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 2,
                            Category = "RPG",
                            CoverImageUrl = "/images/games/witcher3.jpg",
                            Description = "Epic fantasy RPG with rich storytelling",
                            DeveloperId = 4,
                            DownloadCount = 25000,
                            Price = 39.99m,
                            Title = "The Witcher 3"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Action",
                            CoverImageUrl = "/images/games/cod.jpg",
                            Description = "Free-to-play battle royale shooter",
                            DownloadCount = 50000,
                            Price = 0.00m,
                            Title = "Call of Duty: Warzone"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Sandbox",
                            CoverImageUrl = "/images/games/minecraft.jpg",
                            Description = "Build and explore infinite worlds",
                            DownloadCount = 100000,
                            Price = 29.99m,
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Party",
                            CoverImageUrl = "/images/games/amongus.jpg",
                            Description = "Multiplayer party game of teamwork and betrayal",
                            DownloadCount = 75000,
                            Price = 4.99m,
                            Title = "Among Us"
                        });
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Amazing game! Best RPG I've played in years.",
                            CreatedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Great graphics but a bit buggy sometimes.",
                            CreatedAt = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Masterpiece! The story and gameplay are perfect.",
                            CreatedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 2,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Comment = "My childhood game. Still playing in 2024!",
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 4,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Fun with friends but gets repetitive quickly.",
                            CreatedAt = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 5,
                            Rating = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@example.com",
                            IsActive = true,
                            LastLoginAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "password123",
                            Role = "Customer",
                            Username = "john_doe",
                            WalletBalance = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane@example.com",
                            IsActive = true,
                            LastLoginAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "password123",
                            Role = "Customer",
                            Username = "jane_smith",
                            WalletBalance = 75.50m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@arcadex.com",
                            IsActive = true,
                            LastLoginAt = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "admin123",
                            Role = "Admin",
                            Username = "admin_user",
                            WalletBalance = 1000.00m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dev@arcadex.com",
                            IsActive = true,
                            LastLoginAt = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "dev123",
                            Role = "Developer",
                            Username = "game_dev",
                            WalletBalance = 500.00m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "inactive@example.com",
                            IsActive = false,
                            LastLoginAt = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "password123",
                            Role = "Customer",
                            Username = "inactive_user",
                            WalletBalance = 0.00m
                        });
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.Review", b =>
                {
                    b.HasOne("ArcadeX.Api.Models.DomainModels.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcadeX.Api.Models.DomainModels.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.Game", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
