// <auto-generated />
using System;
using ArcadeX.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcadeX.Api.Migrations.ArcadeXDb
{
    [DbContext(typeof(ArcadeXDbContext))]
    [Migration("20260601202055_Fixed the dual DB problem3")]
    partial class FixedthedualDBproblem3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRating")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeveloperId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("GameImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GamePlayUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SystemRequirements")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRating = 4,
                            Category = "[8]",
                            CoverImageUrl = "/images/games/cyberpunk.jpg",
                            Description = "Open-world action RPG set in a dystopian future",
                            DownloadCount = 12500,
                            DownloadUrl = "/downloads/cyberpunk",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = 0,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 2,
                            AgeRating = 4,
                            Category = "[8]",
                            CoverImageUrl = "/images/games/witcher3.jpg",
                            Description = "Epic fantasy RPG with rich storytelling",
                            DownloadCount = 25000,
                            DownloadUrl = "/downloads/witcher3",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = 0,
                            Title = "The Witcher 3"
                        },
                        new
                        {
                            Id = 3,
                            AgeRating = 3,
                            Category = "[0]",
                            CoverImageUrl = "/images/games/cod.jpg",
                            Description = "Free-to-play battle royale shooter",
                            DownloadCount = 50000,
                            DownloadUrl = "/downloads/warzone",
                            Price = 0.00m,
                            ReleaseDate = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = 0,
                            Title = "Call of Duty: Warzone"
                        },
                        new
                        {
                            Id = 4,
                            AgeRating = 1,
                            Category = "[1]",
                            CoverImageUrl = "/images/games/minecraft.jpg",
                            Description = "Build and explore infinite worlds",
                            DownloadCount = 100000,
                            DownloadUrl = "/downloads/minecraft",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = 0,
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 5,
                            AgeRating = 2,
                            Category = "[5]",
                            CoverImageUrl = "/images/games/amongus.jpg",
                            Description = "Multiplayer party game of teamwork and betrayal",
                            DownloadCount = 75000,
                            DownloadUrl = "/downloads/amongus",
                            Price = 4.99m,
                            ReleaseDate = new DateTime(2018, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = 0,
                            Title = "Among Us"
                        });
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Messege")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeopleReviewed")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            Messege = "Amazing game! Best RPG I've played in years.",
                            PeopleReviewed = 0,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            Messege = "Great graphics but a bit buggy sometimes.",
                            PeopleReviewed = 0,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 2,
                            Messege = "Masterpiece! The story and gameplay are perfect.",
                            PeopleReviewed = 0,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 4,
                            Messege = "My childhood game. Still playing in 2024!",
                            PeopleReviewed = 0,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 5,
                            Messege = "Fun with friends but gets repetitive quickly.",
                            PeopleReviewed = 0,
                            Rating = 3.0
                        });
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccountCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.Game", b =>
                {
                    b.HasOne("ArcadeX.Api.Models.DomainModels.User", "Developer")
                        .WithMany("BoughtGames")
                        .HasForeignKey("DeveloperId");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.Review", b =>
                {
                    b.HasOne("ArcadeX.Api.Models.DomainModels.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcadeX.Api.Models.DomainModels.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.Game", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ArcadeX.Api.Models.DomainModels.User", b =>
                {
                    b.Navigation("BoughtGames");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
